### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by ceb-jjgf** [wangze2017/gesture#1]
请问这个项目是在Windows上跑的吗？还是Linux，因为在安装第三方库的时候，有几个库好像只有Linux版本。

**Comment by wangze2017** [comment]
我是在windows上运行的，你说的库具体是什么呢？python版本建议3.7

**Comment by Huasansui** [comment]
请问这个项目公开的这个代码能不能自己训练自己想要的手语，具体要怎么操作一下呢，麻烦解答一下，谢谢。

**Comment by ceb-jjgf** [comment]
> 我是在windows上运行的，你说的库具体是什么？python版本建议3.7

谢谢您的回答，已经成功运行起来了，另外想问一下这个模型是目前只能识别“不好意思”吗？如果需要识别其他的单词需要我们再去用其他视频进行训练对吧？

**Comment by wangze2017** [comment]
> 请问这个项目公开的这个代码能不能自己训练自己想要的手语，具体要怎么操作一下呢，麻烦解答一下，谢谢。

如果想训练其他的手语请看我最新的项目 基于注意力机制的表情识别

**Comment by wangze2017** [comment]
> > 我是在windows上运行的，你说的库具体是什么？python版本建议3.7
> 
> 谢谢您的回答，已经成功运行起来了，另外想问一下这个模型是目前只能识别“不好意思”吗？如果需要识别其他的单词需要我们再去用其他视频进行训练对吧？

如果想训练其他的手语请看我最新的项目 基于注意力机制的表情识别
